@baseUrl = http://localhost:3333

###

# @name healthCheck
GET {{baseUrl}}/health

###

# @name createAccount
POST {{baseUrl}}/accounts
content-type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "securepassword"
}

###

# @name createAccount
POST {{baseUrl}}/accounts
content-type: application/json

{
  "name": "Jenny Doe",
  "email": "jenny.doe@example.com",
  "password": "securepassword"
}

###

# @name authenticateWithPassword
POST {{baseUrl}}/sessions
content-type: application/json

{
  "email": "john.doe@example.com",
  "password": "securepassword"
}

###

# @name authenticateWithGoogle
POST {{baseUrl}}/sessions/google
content-type: application/json

{
  "code": ""
}

###

# @name authenticateWithGithub
POST {{baseUrl}}/sessions/github
content-type: application/json

{
  "code": ""
}

###

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlkYjA4Yy02MjQ0LTdhOTMtYWQ5OS1lY2FkNDc2OWUzZWUiLCJpYXQiOjE3NzY3ODM0OTAsImV4cCI6MTc3NzM4ODI5MH0.-M-fMzCO3mYDBToPpsEoxiqw_DtlCqBYb2ldGsOdk6U

###

# @name getAccount
GET {{baseUrl}}/me
authorization: Bearer {{token}}

###

# @name updateAccountName
PATCH {{baseUrl}}/me/name
content-type: application/json
authorization: Bearer {{token}}

{
  "name": "John Doe"
}

###

# @name updateAccountAvatar
PATCH {{baseUrl}}/me/avatar
content-type: application/json
authorization: Bearer {{token}}

{
  "avatarUrl": "https://avatars.githubusercontent.com/u/1?v=4"
}

###

# @name deleteAccount
DELETE {{baseUrl}}/me
authorization: Bearer {{token}}

###

# @name createOrg
POST {{baseUrl}}/orgs
content-type: application/json
authorization: Bearer {{token}}

{
  "name": "Acme Inc"
}

###

# @name getOrgs
GET {{baseUrl}}/orgs
authorization: Bearer {{token}}

###

# @name getOrg
GET {{baseUrl}}/orgs/acme-inc-9ee7c8
authorization: Bearer {{token}}

###

# @name updateOrgName
PATCH {{baseUrl}}/orgs/acme-inc-9ee7c8/name
content-type: application/json
authorization: Bearer {{token}}

{
  "name": "Acme Inc."
}

###

# @name updateOrgAvatar
PATCH {{baseUrl}}/orgs/acme-inc-9ee7c8/avatar
content-type: application/json
authorization: Bearer {{token}}

{
  "avatarUrl": "https://avatars.githubusercontent.com/u/1?v=4"
}

###

# @name shutdownOrg
DELETE {{baseUrl}}/orgs/acme-inc-9ee7c8
authorization: Bearer {{token}}

###

@userId = 

###

# @name transferOrg
PATCH {{baseUrl}}/orgs/acme-inc-9ee7c8
content-type: application/json
authorization: Bearer {{token}}

{
  "transferToUserId": {{userId}}
}

###

# @name leaveOrg
DELETE {{baseUrl}}/orgs/acme-inc-9ee7c8/leave
authorization: Bearer {{token}}

###

# @name getOrgMembership
GET {{baseUrl}}/orgs/acme-inc-9ee7c8/membership
authorization: Bearer {{token}}